Month 9/step 1
vasaykh2/react-burger pull request #5
Opened 2023-02-24 14:53 UTC by vasaykh2

2023-02-24 15:52 UTC, ArslanDev666 requested changes
## Code Review

Здравствуйте!

Отличная работа.

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Теперь у вас есть роутинг;
- Есть регистрация и авторизация;

### **Но есть несколько замечаний, которые нужно исправить:**

- В файлах, где содержится `jsx`, нужно поменять расширение с `.js` на `.jsx`;

- Доступна должны быть только та ссылка, на которой в данный момент находится пользователь. <https://disk.yandex.com/i/Mpu6dpiifZpeNA>;

- <https://disk.yandex.com/i/_pjEysaX02S5sw> - Вроде бы, шрифт не тот у кнопки, а также кнопку лучше скрывать, если пользователь не выбрал булку (это просто рекомендация, делать не обязательно);

- <https://disk.yandex.com/i/6zeI_748Xjt4Kg> - Нужно отцентрировать контент;

- По чек-листу требуется, чтобы при клике на «История заказов» происходил переход на экран /profile/orders, при этом, ссылка «История заказов» становится активной, а экран /profile/orders пока отображается пустым.

- После нажатия на кнопку сохранить, приложение перестаёт отображать контент, если перезагрузить страницу, всё начинает работать. <https://disk.yandex.com/i/iNn4DaoZtHK_PA>;

- Если авторизированный пользователь перезагрузил страницу `/profile`, он должен остаться на ней. Сейчас он перенаправляется на главную страницу;

- В запросе `/orders` нужно чтобы id у булок были в начале и в конце массива: <https://disk.yandex.com/i/Syv7HD0bN7z1Cw>. А также уберите пустые строки в массиве;

### **Сделает код лучше:**

- Неиспользуемый код следует удалить;

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>

#### **Хочу напомнить, что работа может быть принята, только после исправления всех "Надо исправить". Перед отправкой на ревью, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12).**

2023-02-24 15:52 UTC, ArslanDev666 commented on src/components/profile-form/profile-form.js
> +        value={values.name ? values.name : ''}
**Можно лучше:** 

Лучше написать вот так `value={values.name || ''}`

2023-02-24 15:52 UTC, ArslanDev666 commented on src/services/actions/user.js
> +export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';
**Надо исправить:**

Здесь и далее, это не typescript файл, вам тут не нужно указывать файл.

2023-02-24 15:52 UTC, ArslanDev666 commented on src/services/actions/user.js
> +export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';
**Надо исправить:**

Здесь и далее, это не typescript файл, вам тут не нужно указывать файл.

2023-02-24 15:52 UTC, ArslanDev666 commented on src/utils/api.js
> +  }
**Надо исправить:**

Здесь и далее. Там где вы передаёте `authorization: token`. Вам нужно проверять не истёк ли он.

Лучше сделать отдельный запрос, который будет проверять истёк ли токен, или нет.
Обрабатывать ошибки запросов и при возникновении ошибки jwt expired и вызывать обновление токена при ошибке

Для этого используйте обертку над fetch, примерно такую

```js
// например вот так
export const fetchWithRefresh = async (url, options) => {
  try {
    const res = await fetch(url, options);
    return await checkResponse(res);
  } catch (err) {
    if (err.message === 'jwt expired') {
      const refreshData = await refreshToken();
      if (!refreshData.success) {
        Promise.reject(refreshData);
      }
      localStorage.setItem('refreshToken', refreshData.refreshToken);
      setCookie('accessToken', refreshData.accessToken);
      options.headers.authorization = refreshData.accessToken;
      const res = await fetch(url, options);
      return await checkResponse(res);
    } else {
      return Promise.reject(err);
    }
  }
};
```

2023-02-24 15:52 UTC, ArslanDev666 commented on src/components/burger-constructor/burger-constructor.js
> +            onClick={() => handleOrder(listId)}
**Надо исправить:**

не совсем понимаю, зачем вам тут передавать `listId`, старый вариант был правильным.

также рекомендую вообще отказаться от `listId`. Лучше сразу в функцие `handleOrder` собирать id ингредиентов. 

```js
const ingredientsIds = [bun._id, ...ingredients.map(item => item._id), bun._id];
```

2023-02-24 16:09 UTC, vasaykh2 commented on src/components/profile-form/profile-form.js
> +        value={values.name ? values.name : ''}
Исправил

2023-02-24 16:16 UTC, vasaykh2 commented on src/services/actions/user.js
> +export const REGISTER_FAILED: 'REGISTER_FAILED' = 'REGISTER_FAILED';
Исправил

2023-02-24 18:19 UTC, vasaykh2 commented on src/utils/api.js
> +  }
Исправил

2023-02-24 19:07 UTC, vasaykh2 commented on src/components/burger-constructor/burger-constructor.js
> +            onClick={() => handleOrder(listId)}
Исправил

2023-02-26 09:40 UTC, ArslanDev666 approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

- Все замечания были исправлены;

### **Сделает код лучше:**

- В приложении не должно быть `console.log`;

2023-02-26 09:57 UTC, merged